[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  # This includes the entire project directory including node_modules
  included_files = ["**/*"]
  node_bundler = "esbuild"
